---

- name: create local folder for phantom app
  file:
    path: /opt/splunk/etc/apps/phantom/local
    state: directory
    owner: splunk
    group: splunk

- name: copy phantom.conf to splunk server
  copy:
    src: phantom.conf
    dest: /opt/splunk/etc/apps/phantom/local/phantom.conf
    owner: splunk
    group: splunk
  notify: restart splunk
