---

- name: creating /tmp/{{dump_name}} folder to download attack_data
  file:
    path: /tmp/{{dump_name}}
    state: directory

- name: downloading {{ out }} fromm Git LFS
  get_url:
    url: "{{data}}"
    dest: /tmp/{{ dump_name }}/{{ out }}
    timeout: 300
  when: not (local_data | bool)

- name: Upload replay from local machine
  copy:
    src: ../../attack_data/{{ dump_name }}/{{ out }}
    dest: /tmp/{{ dump_name }}/{{ out }}
  when: local_data | bool

- name: copying DataManipulation.py scripts,update_timestamp set!
  copy:
    src: ../../modules/DatamMnipulation.py
    dest: /tmp/DataManipulation.py
    mode: 755
  when: update_timestamp | bool


- name: running DataManipulation.py, update_timestamp set
  ansible.builtin.shell:
    cmd: /usr/bin/python3 DataManipulation.py --path /tmp/{{dump_name}}/{{out}} --source {{source}} --sourcetype {{sourcetype}}
    chdir: /tmp/
  when: update_timestamp | bool


- name: calling oneshot inputs for indexing
  uri:
    url: https://localhost:8089/services/data/inputs/oneshot
    validate_certs: no
    method: POST
    user: admin
    password: "{{ splunk_password }}"
    force_basic_auth: yes
    body_format: form-urlencoded
    body:
      name: /tmp/{{ dump_name }}/{{ out }}
      sourcetype: "{{ sourcetype }}"
      rename-source: "{{ source }}"
      index: "{{ index }}"
    status_code: 201
