# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
  queue: eddiewebb/queue@volatile
  slack: circleci/slack@3.4.2

dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update -qq
    sudo apt install -y python-dev python3-dev -qq

executors:
  content-executor:
    docker:
      - image: circleci/python:latest
    working_directory: ~/repo

jobs:
  terraform-build-attack-destroy:
    executor: content-executor
    steps:
      - run:
          name: checkout repo
          command: |
            if [[ ! -z "${CIRCLE_PULL_REQUEST}" &&  ! -z "${CIRCLE_PR_NUMBER}" ]]; then
                git clone https://${GITHUB_TOKEN}@github.com/splunk/attack_range.git
                cd attack_range
                git fetch origin pull/${CIRCLE_PR_NUMBER}/head:${CIRCLE_BRANCH}
                git checkout ${CIRCLE_BRANCH}
            elif [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone https://${GITHUB_TOKEN}@github.com/splunk/attack_range.git
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/splunk/attack_range.git
            fi
      - restore_cache:
          key: virtualenv
      - run: *apt-install
      - run:
          name: install python dependencies
          command: |
            cd attack_range
            rm -rf venv
            virtualenv --python=/usr/bin/python3 --clear venv
            source venv/bin/activate
            pip install -q -r requirements.txt
      - save_cache:
          key: virtualenv
          paths:
            - "/attack_range/venv"
      - run:
          name: verify attack_range.py executes
          command: |
            cd attack_range
            source venv/bin/activate
            python attack_range.py --version
      # enable aws cli
      - aws-cli/setup:
          profile-name: default
      # add ssh keys for aws
      - add_ssh_keys:
          fingerprints:
            - "99:5c:9a:45:c2:d0:a6:b6:ea:bd:7a:84:4d:2b:d6:13"
      # init terraform
      - run:
          name: install terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
            sudo unzip terraform_0.12.24_linux_amd64.zip -d /usr/bin
            rm terraform_0.12.24_linux_amd64.zip
            terraform --version
      # do a build using terraform
      - run:
          name: test terraform build, attack, destroy
          command: |
            cd attack_range
            source venv/bin/activate
            # change attack_range default ssh keys
            sed -i "s/key_name = .*$/key_name = attack-range-ci-job/g" attack_range.conf
            sed -i "s/private_key_path =.*$/private_key_path = ~\/.ssh\/id_rsa_995c9a45c2d0a6b6eabd7a844d2bd613/g" attack_range.conf
            sed -i "s/windows_domain_controller = .*$/windows_domain_controller = 1/g" attack_range.conf
            cd terraform/
            terraform init
            cd ..
            python attack_range.py --mode terraform --action build
            python attack_range.py --mode terraform --action simulate --target attack-range-windows-domain-controller --simulation_technique T1003.002
            python attack_range.py --mode terraform --action destroy
      - run:
          name: cleanup terraform on failures
          command: |
            cd attack_range
            source venv/bin/activate
            python attack_range.py --mode terraform --action destroy
          when: on_fail
      - slack/status:
          webhook: '${SLACK_WEBHOOK}'
          fail_only: true
workflows:
  version: 2.1
  build-attack-destroy:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - queue/block_workflow:
          time: '30'
      - terraform-build-attack-destroy:
          filters:
            branches:
              only:
                - develop
          requires:
            - queue/block_workflow
