---
# This playbook contains common tasks in this role

- include_tasks: splunk.yml
- include_tasks: configure_inputs.yml
- include_tasks: configure_indexes.yml
- include_tasks: configure_limits.yml
- include_tasks: configure_web_conf.yml
- include_tasks: configure_server_conf.yml
- include_tasks: create_serverclass.yml

- name: Convert splunk_apps string to list
  set_fact:
    splunk_apps_list: "{{ splunk_server.splunk_apps.split(',') }}"

- name: Include install_app_from_url.yml if s3_bucket_url starts with https
  include_tasks: install_app_from_url.yml
  with_items: "{{ splunk_apps_list }}"
  when: splunk_server.s3_bucket_url is defined and splunk_server.s3_bucket_url.startswith('https')

- name: Include install_app_from_s3.yml if s3_bucket_url doesn't start with https
  include_tasks: install_app_from_s3.yml
  with_items: "{{ splunk_apps_list }}"
  when: splunk_server.s3_bucket_url is not defined or not splunk_server.s3_bucket_url.startswith('https')

- include_tasks: configure_attack_range_dashboard.yml
- include_tasks: configure_escu.yml
- include_tasks: configure_props.yml
- include_tasks: configure_cim.yml
- include_tasks: configure_phantom.yml
