---
# Install Phantom from RPM on a fresh CentOS 7 instance

- name: Change mirror to vault.centos.org
  shell: sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
  become: yes

- name: Uncomment baseurl lines
  shell: sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
  become: yes

- name: Comment out mirrorlist lines
  shell: sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
  become: yes

- name: Update all packages
  become: yes
  become_user: root
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Copy Splunk SOAR to server
  become: yes
  become_user: root
  unarchive:
    src: "../../apps/{{ phantom_server.phantom_app }}"
    dest: /home/ec2-user
    owner: ec2-user
    group: ec2-user

- name: Creates directory
  become: yes
  become_user: root
  file:
    path: /opt/soar
    state: directory
    owner: ec2-user
    group: ec2-user

- name: prepare phantom install script without apps
  become: yes
  command: /home/ec2-user/splunk-soar/soar-prepare-system --splunk-soar-home /opt/soar --no-prompt 

- name: copy splunk soar folder
  become: yes
  become_user: root
  command: cp -r /home/ec2-user/splunk-soar /home/phantom/splunk-soar

- name: chown splunk soar folder
  become: yes
  become_user: root
  command: chown -R phantom:phantom /home/phantom/splunk-soar

- name: run the phantom install script 
  become: yes
  become_user: phantom
  command: ./soar-install --splunk-soar-home /opt/soar --no-prompt --ignore-warnings
  args:
    chdir: /home/phantom/splunk-soar