---

- name: create local folder for phantom app
  file:
    path: /opt/splunk/etc/apps/phantom/local
    state: directory
    owner: splunk
    group: splunk

- name: copy phantom.conf to splunk server
  copy:
    src: phantom.conf
    dest: /opt/splunk/etc/apps/phantom/local/phantom.conf
    owner: splunk
    group: splunk

- name: restart splunk
  service: name=splunk state=restarted
  become: yes

- name: Connect Splunk Phantom App with Phantom
  shell: curl -k -u "admin:{{ attack_range_password }}" --data '{"verify_certs":"false","enable_logging":"false","config":[{"ph-auth-token":"{{ phantom_byo_api_token | replace("=","%3D") | replace("+","%2B") }}","server":"https://{{ phantom_byo_ip }}","custom_name":"phantom","default":false,"user":"","ph_auth_config_id":"193b2ffc-48fb-4087-bc75-c44184e7fa07","proxy":"","validate":true}],"accepted":"true","save":true}' https://localhost:8089/services/update_phantom_config?output_mode=json
  register: shell_output

- debug: 
    var: shell_output

- name: restart splunk
  service: name=splunk state=restarted
  become: yes 