---
- name: Dump
  hosts: win*
  tasks:
  - name: Facts
    setup:
  - name: Dump
    delegate_to: localhost
    run_once: true
    copy:
      content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
      dest: /tmp/setup-dump.json
