- hosts: dc
  gather_facts: True
#  tasks:
#    - debug:
#        msg: "{{ hostvars[inventory_hostname] }}"
  roles:
    - common
    - windows_dns_server
    - windows_domain_controller
    - universal_forwarder
    - firedrill
    - sysmon
  vars_files:
    - ../vars/vars.yml 
