- hosts: all
  gather_facts: True
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
    hostname: win-client
  roles:
    - windows_common
    - windows_domain_client
    - windows_universal_forwarder
    - windows_caldera_agent
    - sysmon
