
general:
  attack_range_password: "Pl3ase-k1Ll-me:p1"
  cloud_provider: "aws"
  key_name: "attack-range-key-pair"
  attack_range_name: "ar"
  ip_whitelist: "0.0.0.0/0"
  version: "3.0.0"
  crowdstrike_falcon: "0"
  crowdstrike_agent_name: "WindowsSensor.exe"
  crowdstrike_customer_ID: ""
  crowdstrike_logs_region: ""
  crowdstrike_logs_access_key_id: ""
  crowdstrike_logs_secret_access_key: ""
  crowdstrike_logs_sqs_url: ""
  carbon_black_cloud: "0"
  carbon_black_cloud_agent_name: "installer_vista_win7_win8-64-3.8.0.627.msi"
  carbon_black_cloud_company_code: ""
  carbon_black_cloud_s3_bucket: ""
aws:
  region: "eu-central-1"
  private_key_path: "~/.ssh/id_rsa"
  cloudtrail: "0"
  cloudtrail_sqs_queue: "https://sqs.us-west-2.amazonaws.com/111111111111/cloudtrail-cloud-attack-range"
azure:
  region: "West Europe"
  subscription_id: "xxx"
  private_key_path: "~/.ssh/id_rsa"
  public_key_path: "~/.ssh/id_rsa.pub"
  azure_logging: "0"
  app_id: "xxx"
  client_secret: "xxx"
  tenant_id: "xxx"
  event_hub_name: "xxx"
  event_hub_host_name: "xxx"
local:
  provider: "Virtual Box"
splunk_server:
  image: "splunk-v3-0-0"
  install_es: "0"
  splunk_es_app: "splunk-enterprise-security_701.spl"
phantom_server:
  phantom_server: "0"
  phantom_community_username: user
  phantom_community_password: password
  phantom_repo_url: https://repo.phantom.us/phantom/5.2/base/7/x86_64/phantom_repo-5.2.1.78411-1.x86_64.rpm
  phantom_version: "5.2.1.78411-1"
windows_servers_default:
  hostname: ar-win 
  image: windows-2016-v3-0-0
  create_domain: "0"
  join_domain: "0"
  win_sysmon_config: "SwiftOnSecurity.xml"
  install_red_team_tools: "0"
  bad_blood: "0"
linux_servers_default:
  hostname: ar-linux
  image: linux-v3-0-0
  sysmon_config: "SysMonLinux-CatchAll.xml"
kali_server:
  kali_server: "0"
nginx_server:
  nginx_server: "0"
  image: nginx-web-proxy-v3-0-0
  proxy_server_ip: "10.0.1.12"
  proxy_server_port: "8000"
zeek_server:
  zeek_server: "0"
  image: "zeek-v3-0-0"
simulation:
  atomic_red_team_repo: redcanaryco
  atomic_red_team_branch: master
  prelude: "0"
  prelude_operator_url: "https://download.prelude.org/latest?arch=x64&platform=linux&variant=zip&edition=headless"
  prelude_account_email: "test@test.com"
