
general:
  attack_range_password: "Pl3ase-k1Ll-me:p123"
  cloud_provider: "aws"
  key_name: "ar-github-actions"
aws:
  region: "eu-central-1"
  private_key_path: "~/.ssh/ar-github-actions"
windows_servers: 
  - hostname: ar-win
    image: windows-2016-v3-0-0