- name: Check we have downloaded stream
  win_stat:
    path: C:\splunk-stream.zip
  register: stream_zip

- name: Download Stream TA from S3 bucket
  when: stream_zip.stat.exists == False
  win_shell: |
    [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"
    (New-Object System.Net.WebClient).DownloadFile("https://attack-range-appbinaries.s3-us-west-2.amazonaws.com/{{ splunk_stream_ta }}", "C:\splunk-stream.zip")

- name: Check we have unzip streams TA
  win_stat:
    path: "C:\\Program Files\\SplunkUniversalForwarder\\etc\\apps\\Splunk_TA_stream"
  register: stream_ta

- name: Unzip Stream App
  win_unzip:
    src: C:\splunk-stream.zip
    dest: "C:\\Program Files\\SplunkUniversalForwarder\\etc\\apps\\"
    when: stream_app.stat.exists == False || stream_ta.stat.exists == False

- name: Copy Stream Config File
  win_template:
    src: inputs.conf.j2
    dest: "C:\\Program Files\\SplunkUniversalForwarder\\etc\\apps\\Splunk_TA_stream\\local\\inputs.conf"
