---
# This playbook contains common tasks in this role

- include: splunk.yml
- include: configure_inputs.yml
- include: configure_indexes.yml
- include: configure_limits.yml
- include: configure_web_conf.yml
- include: configure_server_conf.yml
- include: configure_props.yml
- include: create_serverclass.yml
- include: install_botsv3_dataset.yml
- include: install_app_from_s3.yml
  with_items:
    - "splunk-add-on-for-microsoft-windows_840.tgz"
    - "splunk-timeline-custom-visualization_161.tgz"
    - "status-indicator-custom-visualization_150.tgz"
    - "punchcard-custom-visualization_150.tgz"
    - "splunk_attack_range_reporting-1.0.7.tar.gz"
    - "splunk-common-information-model-cim_500.tgz"
    - "DA-ESS-ContentUpdate-latest.tar.gz"
    - "python-for-scientific-computing-for-linux-64-bit_302.tgz"
    - "splunk-machine-learning-toolkit_531.tgz"
    - "splunk-security-essentials_350.tgz"
    - "splunk-add-on-for-sysmon_200.tgz"
    - "add-on-for-linux-sysmon_104.tgz"
    - "splunk-add-on-for-amazon-web-services-aws_520.tgz"
    - "splunk-add-on-for-microsoft-office-365_300.tgz"
    - "splunk-add-on-for-amazon-kinesis-firehose_131r7d1d093.tgz"
    - "splunk-add-on-for-unix-and-linux_840.tgz"
    - "ta-for-zeek_105.tgz"
    - "splunk-add-on-for-nginx_310.tgz"
    - "phantom-app-for-splunk_4035.tgz"
- include: configure_attack_range_dashboard.yml
- include: configure_escu.yml
- include: configure_cim.yml
- include: configure_phantom.yml
#- include: install_stream_app.yml
