---
# Install Phantom from RPM on a fresh CentOS 7 instance

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: check if phantom is installed
  stat: path=/opt/phantom
  register: phantom_path

- name: debug print if phantom is installed
  debug: msg='phantom is already installed under /opt/phantom'
  when: phantom_path.stat.exists


- name: install the phantom setup rpm from the community repository
  yum:
    name: '{{ phantom_repo_url }}'
    state: present

# installing apps takes 15+ minutes longer, so later we will install just the apps we need
- name: run the phantom install script without apps
  shell: printf "{{phantom_community_username}}\n{{phantom_community_password}}\n" | /opt/phantom/bin/phantom_setup.sh install --no-prompt --without-apps --version=5.2.0.77965-1
  async: 600
  poll: 60
